import {
  readFile,
  writeFile,
  mkdir,
  readdir,
  copyFile,
} from "node:fs/promises";
import { dirname, resolve, join } from "node:path";
import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";

const root = dirname(fileURLToPath(import.meta.url));
const input = JSON.parse(
  await readFile(join(root, "design/tokens.json"), "utf8"),
);
const declarations = (obj) =>
  Object.entries(obj)
    .map(([key, value]) => `  --${key}: ${value};`)
    .join("\n");
const aliases = declarations(
  Object.fromEntries(
    Object.entries(input.aliases).map(([key, value]) => [
      key,
      `var(--${value})`,
    ]),
  ),
);
const css = `/* Generated by design-system/build.mjs. Edit design/tokens.json. */\n:root {\n${declarations(input.tokens)}\n${declarations(input.light)}\n${aliases}\n  color-scheme: light;\n}\n:root[data-theme="dark"], .section--dark {\n${declarations(input.dark)}\n${aliases}\n  color-scheme: dark;\n}\n:root[data-theme="light"], .section--light {\n${declarations(input.light)}\n${aliases}\n  color-scheme: light;\n}\n`;
const check = process.argv.includes("--check");
if (check) {
  if ((await readFile(join(root, "tokens.css"), "utf8")) !== css)
    throw new Error("Stale tokens.css. Run node design-system/build.mjs.");
} else await writeFile(join(root, "tokens.css"), css);

// The user explicitly requires the original blue/grey asset, byte for byte.
const original = join(root, "assets/mark-source.svg");
try {
  const mark = await readFile(original, "utf8");
  if (check) {
    if ((await readFile(join(root, "assets/mark.svg"), "utf8")) !== mark)
      throw new Error("Stale mark.svg");
  } else await writeFile(join(root, "assets/mark.svg"), mark);
} catch (error) {
  throw error;
}

async function files(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  return (
    await Promise.all(
      entries.map(async (item) =>
        item.isDirectory()
          ? files(join(dir, item.name))
          : [join(dir, item.name)],
      ),
    )
  ).flat();
}
const targetIndex = process.argv.indexOf("--sync");
if (targetIndex !== -1) {
  if (check) throw new Error("--sync cannot be used with --check");
  const target = resolve(process.argv[targetIndex + 1]);
  if (target === root || target.startsWith(root + "/") || !target.endsWith("design-system"))
    throw new Error("Target must be another design-system directory.");
  for (const file of await files(root)) {
    const dest = join(target, file.slice(root.length + 1));
    await mkdir(dirname(dest), { recursive: true });
    await copyFile(file, dest);
  }
  console.log(`Synchronized xSOM Signal ${input.meta.version} to ${target}`);
}
const compareIndex = process.argv.indexOf("--compare");
if (compareIndex !== -1) {
  const target = resolve(process.argv[compareIndex + 1]);
  const sourceFiles = (await files(root)).map(file => file.slice(root.length + 1)).sort();
  const targetFiles = (await files(target)).map(file => file.slice(target.length + 1)).sort();
  if (JSON.stringify(sourceFiles) !== JSON.stringify(targetFiles)) throw new Error("Shared package file inventories differ.");
  for (const file of sourceFiles) {
    const [source, destination] = await Promise.all([readFile(join(root, file)), readFile(join(target, file))]);
    if (!source.equals(destination)) throw new Error(`Shared package drift: ${file}`);
  }
  console.log(`Shared package verified byte-for-byte: ${sourceFiles.length} files.`);
}
const digest = createHash("sha256").update(css).digest("hex");
console.log(
  `xSOM Signal ${input.meta.version}: ${check ? "checked" : "generated"} tokens ${digest.slice(0, 16)}`,
);
